#! /bin/sh
### BEGIN INIT INFO
# Provides:             tracks
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    OpenBSD Secure Shell server
### END INIT INFO

# This is a generic Init Script
# This is a comment/note

#Edit these variables!
TRACKS_DIR=/opt/tracks/current
cd $TRACKS_DIR
#wait 10 seconds to start the tracks app
sleep 10
case "$1" in
  start)
    echo "Starting Tracks"
    bundle exec rails server -e production &
    ;;
  stop)
    echo "shutting down Tracks"
     kill -15 $(cat /opt/tracks/s/pids/server.pid)
    ;;
  *)
    echo "Usage: /etc/init.d/tracks {start|stop}"
    exit 1
    ;;
esac

exit 0
